try{ // tentar 
    console.log(naoexiste);
}catch(err){ // se de erro executa o catch
    console.log("Ocorreu um erro!");
}


